### PR TITLE
Update Main.php

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by matthew4444** [comment]
hello my birthday is tomorow,waa ,and i can make a website if u need it

**Comment by matthew4444** [comment]
and can i be in the group

**Comment by matthew4444** [comment]
i need a friend

**Comment by erkam2002** [comment]
?

**Comment by matthew4444** [comment]
im matthew ,remeber me

**Comment by matthew4444** [comment]
?

**Comment by JameelDev** [comment]
Sure you can join Matthew

**Comment by JameelDev** [comment]
Matthew yes can you make a website too

**Pull request closed without merging**
